scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'server'
    static_configs:
      - targets: ['server:5000']
  - job_name: 'client'
    static_configs:
      - targets: ['client:5000']
  - job_name: 'interface'
    static_configs:
      - targets: ['interface:8081']

  - job_name: 'node resources'
    dns_sd_configs:
      - names: ['tasks.node']
        type: 'A'
        port: 9100
    params:
      collect[]:
        - cpu
        - meminfo
        - diskstats
        - netdev
        - netstat

  - job_name: 'node storage'
    scrape_interval: 1m
    dns_sd_configs:
      - names: ['tasks.node']
        type: 'A'
        port: 9100
    params:
      collect[]:
        - filefd
        - filesystem
        - xfs

  - job_name: 'cadvisor'
    dns_sd_configs:
      - names: ['tasks.cadvisor']
        type: 'A'
        port: 8080
